### ISSUE TITLE
Update user stories

### ISSUE THREAD

**Issue by MonikaTheiss** [COS301-SE-2024/GameOnConnect#144]

**Comment by MonikaTheiss** [comment]
@shan-226 and @pieryvdl please have a look at the updated user stories page on the wiki and let me know what I can change. I have also created an appendix page with the user stories version 1 information. Let me know what you think!

**Comment by pieryvdl** [comment]
I tried to check it out in the wiki, but don't see the page there? I think the link might have been broken?

**Comment by MonikaTheiss** [comment]
Should work now, accidentally changed the name and didnt think the link would have to updated

**Comment by shan-226** [comment]
It looks good to me!

**Comment by pieryvdl** [comment]
Appendix looks good, I would change these user stories: 
18. As a user, I want to see the friends of my own friends' profiles, so that I can also connect with them.
19. As a user, I want to be able to navigate and only view the the retailer page for any game. 

I would change 19 or reword it, because we are not providing the ability to buy the game, I'm not sure, it just feels we are over promising. On 18 we should be specific about viewing the profiles of the friends.

**Comment by MonikaTheiss** [comment]
Ok cool , thanks for the feedback , will quickly make the suggested changes 👍

**Comment by MonikaTheiss** [comment]
Made the changes, please let me know if I need to change anything else @pieryvdl ?
