### ISSUE TITLE
Frontend - Create User profile

### ISSUE THREAD

**Issue by MonikaTheiss** [COS301-SE-2024/GameOnConnect#43]

**Comment by LeratoKgomo** [comment]
NB this issue is for the static page

**Comment by LeratoKgomo** [comment]
@pieryvdl Can you please review the Profile page in the feat/Profile_page branch

**Comment by pieryvdl** [comment]
Hi Lerato, so I can only give a formal review once there is a pull request, but here are some things I' see so far. The back button needs to be fixed with proper routing. You can maybe put a container from "Game Name" to the bottom so that we can create "cards" for the games, then the bottom navigation should be added. I think we cna build it in a seperate page, so just wait with that for now. Overall , I really like it it looks great! Thank you!

**Comment by MonikaTheiss** [comment]
@LeratoKgomo can you please close this issue?
